// <auto-generated />
namespace Dynamic_Web_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDefaultStatusValueAltKategori : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDefaultStatusValueAltKategori));
        
        string IMigrationMetadata.Id
        {
            get { return "202505080943389_AddDefaultStatusValueAltKategori"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
